# Defines two organizations
#  - Orderer organization
#  - Org1  = Single peer organization
#    Uses the "Specs" to declare the peers instead of Template

##### Orderer for acme
OrdererOrgs:
  - Name: Rnp
    Domain: rnp.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      
#### Peers for acme
PeerOrgs:
  # Peer configuration for ACME
  - Name: Org1
    Domain: rnp.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: devpeer
        CommonName: devpeer
    Users:
      Count: 2



      